### ISSUE TITLE
import error no module named AV

### ISSUE THREAD

**Issue by matiarj** [pupil-labs/PyAV#3]
i try running pupil and i get import error no module named av

after trying to reinstall pyAV i get this

viktor@viktor-Precision-WorkStation-490:~/PyAV$ sudo python setup.py install
running install
running bdist_egg
running egg_info
writing av.egg-info/PKG-INFO
writing top-level names to av.egg-info/top_level.txt
writing dependency_links to av.egg-info/dependency_links.txt
writing entry points to av.egg-info/entry_points.txt
reading manifest file 'av.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no files found matching '*.c' under directory 'src'
writing manifest file 'av.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
running build_ext
running reflect
running config
looking for avformat_open_input... missing
looking for pyav_function_should_not_exist... missing
looking for av_calloc... found
looking for av_frame_get_best_effort_timestamp... found
looking for avformat_alloc_output_context2... missing
looking for avformat_close_input... missing
looking for AVStream.index... found
looking for PyAV.struct_should_not_exist... missing
looking for AVFrame.mb_type... missing

We didn't find `avformat_open_input` in the libraries.
We look for it only as a sanity check to make sure the build
process is working as expected. It is not, so we must abort.

Please open a ticket at https://github.com/mikeboers/PyAV/issues
with the folowing information:

PyAV: 0.3.0 v0.3.0-18-g498516d
Python: 2.7.6 (default, Jun 22 2015, 17:58:13) \n[GCC 4.8.2]
platform: Linux-3.19.0-39-generic-x86_64-with-Ubuntu-14.04-trusty
extension_extra:
    libraries: ['avcodec', 'avdevice', 'avformat', 'avutil', 'swresample', 'swscale']
    library_dirs: ['/usr/local/lib']
    include_dirs: ['/usr/local/include', 'include', '/usr/include/python2.7']
config_macros:
    PYAV_VERSION=0.3.0
    PYAV_VERSION_STR="0.3.0"
    PYAV_COMMIT_STR="v0.3.0-18-g498516d"
    PYAV_HAVE_LIBSWRESAMPLE=1
    PYAV_HAVE_AV_CALLOC=1
    PYAV_HAVE_AV_FRAME_GET_BEST_EFFORT_TIMESTAMP=1

**Comment by mkassner** [comment]
I this issues belongs here: https://github.com/mikeboers/PyAV/issues
